### ISSUE TITLE
SwiftProtobuf.framework error during Xcode Build

### ISSUE THREAD

**Issue by tcote19** [thepoweroftwo/meshtastic-ios#3]
I've cloned the repo into Xcode but receive this error while trying to simulate the project:

/Users/thomascote/Documents/meshtastic-ios/Meshtastic.xcodeproj Building for iOS Simulator, but the linked and embedded framework 'SwiftProtobuf.framework' was built for iOS.

Any ideas as to what might be causing this?

**Comment by thepoweroftwo** [comment]
The framework was built for arm architecture. To run it in simulator you need the framework compiled for x64. 
But it makes no sense to run the project in simulator because there is no bluetooth. 
If you use iOS hardware it will work

**Comment by tcote19** [comment]
Thank you, I confirmed it runs fine with the iPhone hardware instead of simulator.
Closing.
