### ISSUE TITLE
xCode 12: error Module compiled with Swift 5.3.1 cannot be imported by the Swift 5.4.2 compiler

### ISSUE THREAD

**Issue by krl91** [thepoweroftwo/meshtastic-ios#5]
Hi,
I try to build the current source code but I have the error "Module compiled with Swift 5.3.1 cannot be imported by the Swift 5.4.2 compiler" portnums.pb.swift , on line 11 "import SwiftProtobuf"

Is there any work around? I tryied to set the Build Libraries for Distribution option to Yes without success.

But anyway this file was generated automatically, can you put the source?

Thank you

**Comment by matt-redfirm** [comment]
Is there any progress on this error, I cannot compile the project

**Comment by thepoweroftwo** [comment]
It should work now. See https://github.com/thepoweroftwo/meshtastic-ios/commit/b1aaa483b6c081b5b00f5a6ce1c4d781ea7df99e

If the issue persists, feel free to open a new one. Thank you!
